# Generated by Django 3.2.7 on 2021-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=5000)),
                ('saltvalue', models.CharField(max_length=5000)),
                ('confirmpassword', models.CharField(max_length=5000)),
            ],
        ),
    ]
