# Generated by Django 3.2.7 on 2021-10-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details_db',
            name='confirmpassword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_details_db',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
