# Generated by Django 3.2.7 on 2021-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Intelligence', '0002_auto_20211011_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details_db',
            name='saltvalue',
            field=models.CharField(max_length=10000),
        ),
    ]
