# Generated by Django 3.2.7 on 2021-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Intelligence', '0004_auto_20211011_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details_db',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_details_db',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
