# Generated by Django 3.2.7 on 2021-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Intelligence', '0005_auto_20211011_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details_db',
            name='saltvalue',
            field=models.BinaryField(max_length=1000),
        ),
    ]
