# Generated by Django 3.2.7 on 2021-11-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Intelligence', '0008_auto_20211013_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details_db',
            name='confirmpassword',
        ),
    ]
